pipeline{
    agent any
    environment{
        DOCKERHUB_CREDS = credentials('dockerhub')
        TAG = sh(returnStdout: true, script: "git rev-parse --short=10 HEAD").trim()
    }

    stages{
        stage('Clone Repo'){
            steps{
                echo "Checking out code..."
                checkout scm
                sh 'ls *'
            }
        }
        stage('Build image'){
            steps{
                echo "Building Docker image... ${BUILD_NUMBER}"
                echo "Tag with latest commit id: ${TAG}"
                sh 'docker build -t rsxyz123/jenkinstest:${TAG} ./pushdockerimage/'
            }
        } 
        stage('Docker Login'){
            steps{
                echo "Login to DockerHub..."
                sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin' 
            }
        } 
        stage('Docker Push'){
            steps{
                echo "Push image to DockerHub..."
                sh 'docker push rsxyz123/jenkinstest:${TAG}' 
            }
        }                   
    }
    post{
        always{
            sh 'docker logout'
        }
    }
}
